from typing import List, Dict
from api.schemas import ArabicTerm
from memory.sovereign_memory import sovereign_memory

class ArabizationEngine:
    """
    RF-020: Intelligent Arabization System.
    """
    
    def __init__(self):
        self.memory = sovereign_memory

    def arabize(self, english_term: str) -> ArabicTerm:
        """
        Main entry point for arabizing a term.
        Strategy:
        1. Check Memory (ChromaDB/Graph)
        2. Check Static Dictionary (Placeholder)
        3. Generative Creation (Future: LLM)
        """
        
        # 1. Check Memory
        existing = self.memory.find_term(english_term, n_results=1)
        if existing:
            # Reconstruct ArabicTerm from metadata
            # Note: This is a simplified reconstruction
            data = existing[0]
            return ArabicTerm(
                id=data.get('id', 'unknown'),
                english_term=english_term,
                arabic_translation=data.get('arabic_translation', ''),
                source="memory",
                confidence=float(data.get('confidence', 1.0)),
                definition=data.get('definition', '')
            )
            
        # 2. Static Dictionary / Fallback (Placeholder)
        # In V2 full implementation, this calls an LLM or specific API
        static_db = {
            "strategy": "استراتيجية",
            "logistics": "لوجستيات",
            "agent": "وكيل",
            "sovereign": "سيادي"
        }
        
        if english_term.lower() in static_db:
            return ArabicTerm(
                id=f"auto_{english_term}",
                english_term=english_term,
                arabic_translation=static_db[english_term.lower()],
                source="static_dictionary",
                confidence=0.9,
                definition="Autogenerated from static DB"
            )
            
        # 3. Fallback
        return ArabicTerm(
            id=f"new_{english_term}",
            english_term=english_term,
            arabic_translation=f"[{english_term}]", # Mark for review
            source="unknown",
            confidence=0.0,
            definition="Needs human review"
        )
